### ISSUE TITLE
postgres: duplicate key

### ISSUE THREAD

**Issue by mvysny** [mvysny/renogy-klient#1]
Sometimes (especially on slow devices) there are the following logs:
```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "log_pkey"
  Detail: Key (datetime)=(1685685275) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:268)
        at PostgresDataLogger.sql(DataLogger.kt:198)
        at PostgresDataLogger.append(DataLogger.kt:270)
```
Probably, if the previous scan is delayed by 10 seconds, there are two consecutive scans in rapid succession, trying to insert the same timestamp into the postgresql database.

**Comment by mvysny** [comment]
UPSERT solves this: https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

The `ON CONFLICT DO UPDATE` sounds like a good way since the data will be updated with the newest one.
