### ISSUE TITLE
influxdb2 sometimes fails with error 500

### ISSUE THREAD

**Issue by mvysny** [mvysny/renogy-klient#8]
Retry a couple of times in such case. Stacktrace:
```
2023-10-10 12:46:02.805 [pool-1-thread-1] WARN Main - Main loop failure                                                                                                                
java.lang.IllegalStateException: InfluxDB2 failed: 500 {"code":"internal error","message":"unexpected error writing points to database: timeout"}                                      
        at datalogger.InfluxDB2Logger.execPost(InfluxDB2Logger.kt:86)                                                                                                                  
        at datalogger.InfluxDB2Logger.append(InfluxDB2Logger.kt:76)                                                                                                                    
        at datalogger.CompositeDataLogger.append(DataLogger.kt:38)                                                                                                                     
        at MainKt$mainLoop$2.invoke(Main.kt:61)                                                                                                                                        
        at MainKt$mainLoop$2.invoke(Main.kt:55)                                                                                                                                        
        at utils.UtilsKt.scheduleAtFixedRate_8Mi8wO0$lambda$1(Utils.kt:64)                                                                                                             
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:576)                                                                                           
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)                                                                                                  
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)                                                    
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)                                                                                   
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)                                                                                   
        at java.base/java.lang.Thread.run(Thread.java:1623)                           
```

**Comment by mvysny** [comment]
Also retry java.net.ConnectException
